version: '3.8'

services:
  backend:
    image: shuu005/music_recommender_jtp:backend  # using DockerHub image
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    image: shuu005/music_recommender_jtp:frontend  # using DockerHub image
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge