version: '3.8'

services:
  backend: # works for backend 
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1 #this is new; sends logs in real time
    networks:
      - app-network #this is the network we created

  frontend: # works for frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8000 #build time arguement
    ports:
      - "80:80"  
    environment:
      - VITE_API_BASE_URL=http://localhost:8000 #environment variable; will fail without this
    depends_on:
      - backend #depends upon backend service; backend starts before frontend
    networks:
      - app-network #this is the network we created

networks:
  app-network:
    driver: bridge #bridge network for containers to communicate